### ISSUE TITLE
Projects support

### ISSUE THREAD

**Issue by login4all** [UGroup/Atom-COS-Studio#29]
Add support for the Caché studio projects feature in separate tab on a TreeView
- config  for whole project
- web apps and project settings for stored it in remote repo
- default project store
  Related tasks 
  - [ ] wait until finished or documented "Multiple folders in projects" issue atom/atom#770
  - [ ] allow individual project files danielbrodin/atom-project-manager#25
  - [ ] remote web apps #26
  - [ ] multiple web apps #20 
  - [ ] default project #27
  - [ ] project tab #28
